version: '3'

services:
  web:
    build: .
    image: registry.k8s.spettl.net/mailadmin:0.0.4
    environment:
      - DATABASE_URL=mysql2://mailadmin:@localhost/mailadmin_production
      - MAILSERVER_HOSTNAME=mail.example.com
      - WEBMAIL_HOSTNAME=webmail.example.com
      - API_TOKEN=secret
    ports:
      - "3000:3000"
    volumes:
      - "/var/run/mysqld:/var/run/mysqld"
