name: CI

on: [push, pull_request]

jobs:
  test:
    name: Rails tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Start MySQL server
        run: sudo systemctl start mysql.service
      - name: Create database
        run: bundle exec rails db:create
        env:
          DATABASE_URL: mysql2://root:root@localhost/mailadmin_test
      - name: Run tests
        run: bundle exec rails test:all
        env:
          DATABASE_URL: mysql2://root:root@localhost/mailadmin_test
      - name: Run rubocop
        run: bundle exec rubocop -c .rubocop.yml
