name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Build and publish images
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0
          driver-opts: image=moby/buildkit:v0.9.0
          buildkitd-flags: --debug
      - name: Docker metadata for mailadmin
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aspettl/mailadmin
          flavor: |
            latest=false
          tags: |
            type=edge
            type=ref,event=tag
            type=ref,event=pr
      - name: Docker metadata for configreload
        id: meta_configreload
        uses: docker/metadata-action@v3
        with:
          images: aspettl/docker-mailserver-configreload
          flavor: |
            latest=false
          tags: |
            type=edge
            type=ref,event=tag
            type=ref,event=pr
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push mailadmin
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
      - name: Build and push docker-mailserver-configreload
        uses: docker/build-push-action@v2
        with:
          context: integrations/docker-mailserver-configreload
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_configreload.outputs.tags }}
          labels: ${{ steps.meta_configreload.outputs.labels }}
